version: "3"
services:
  webapp:
    image: douglira/multi-webapp
    mem_limit: 128m
    hostname: webapp

  api:
    image: douglira/multi-server
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGHOST=$PGHOST
      - PGPORT=$PGPORT
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGDATABASE=$PGDATABASE

  worker:
    image: douglira/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  nginx:
    image: douglira/multi-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"